Repository kubernetes-csi/external-attacher, pull requests merged in 2018-10, with the labels that each got.

#74 Update vendor files to point to release 1.12.0
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/Godeps/Godeps.json
  vendor/k8s.io/api/autoscaling/v2beta2/generated.proto
  vendor/k8s.io/api/autoscaling/v2beta2/types.go
  vendor/k8s.io/api/batch/v1/generated.pb.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/batch/v1/zz_generated.deepcopy.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apimachinery/Godeps/Godeps.json
  vendor/k8s.io/apimachinery/pkg/apis/config/v1alpha1/register.go
  vendor/k8s.io/client-go/.travis.yml
  vendor/k8s.io/client-go/Godeps/Godeps.json
  vendor/k8s.io/client-go/INSTALL.md
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp_test.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/rest/request_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#75 replace pr url with design spec in community repo
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#76 Set dependency based on a tag kubernetes-1.12.0
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/client-go/Godeps/Godeps.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#77 Cherry-pick vendor files changes to point to K8S 1.12.0
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/Godeps/Godeps.json
  vendor/k8s.io/api/autoscaling/v2beta2/generated.proto
  vendor/k8s.io/api/autoscaling/v2beta2/types.go
  vendor/k8s.io/api/batch/v1/generated.pb.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/batch/v1/zz_generated.deepcopy.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apimachinery/Godeps/Godeps.json
  vendor/k8s.io/apimachinery/pkg/apis/config/v1alpha1/register.go
  vendor/k8s.io/client-go/.travis.yml
  vendor/k8s.io/client-go/Godeps/Godeps.json
  vendor/k8s.io/client-go/INSTALL.md
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp_test.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/rest/request_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#81 Update tag to 0.4.1
  Makefile
Labels: size/XS

#84 deploy: split out RBAC definitions
  deploy/kubernetes/deployment.yaml
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#85 start attach controller inside OnStartedLeading callback
  cmd/csi-attacher/leader.go
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#78 Add CSI Migration logic for attach/detach
  Gopkg.lock
  Gopkg.toml
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/.gitignore
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/Gopkg.lock
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/Gopkg.toml
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/LICENSE
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/OWNERS
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/README.md
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/RELEASE.md
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/SECURITY_CONTACTS
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/code-of-conduct.md
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/plugins/aws_ebs.go
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/plugins/gce_pd.go
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/plugins/in_tree_volume.go
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/translate.go
  vendor/github.com/kubernetes-csi/kubernetes-csi-migration-library/translate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
