Repository kubernetes-csi/external-attacher, pull requests merged in 2018-11, with the labels that each got.

#86 Store NodeID in annotation
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/trivial_handler_test.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#87 rbac: fix kubectl validation error
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#89 Update external-attacher to use CSI spec 1.0
  Gopkg.lock
  Gopkg.toml
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  pkg/controller/framework_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  vendor/github.com/container-storage-interface/spec/.gitignore
  vendor/github.com/container-storage-interface/spec/.travis.yml
  vendor/github.com/container-storage-interface/spec/CCLA.pdf
  vendor/github.com/container-storage-interface/spec/CONTRIBUTING.md
  vendor/github.com/container-storage-interface/spec/OWNERS
  vendor/github.com/container-storage-interface/spec/README.md
  vendor/github.com/container-storage-interface/spec/VERSION
  vendor/github.com/container-storage-interface/spec/csi.proto
  vendor/github.com/container-storage-interface/spec/lib/go/Makefile
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/spec.md
  vendor/github.com/kubernetes-csi/csi-test/.gitignore
  vendor/github.com/kubernetes-csi/csi-test/.travis.yml
  vendor/github.com/kubernetes-csi/csi-test/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/csi-test/Gopkg.lock
  vendor/github.com/kubernetes-csi/csi-test/Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-test/Makefile
  vendor/github.com/kubernetes-csi/csi-test/OWNERS
  vendor/github.com/kubernetes-csi/csi-test/README.md
  vendor/github.com/kubernetes-csi/csi-test/SECURITY_CONTACTS
  vendor/github.com/kubernetes-csi/csi-test/cmd/csi-sanity/sanity_test.go
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.go
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.mock.go
  vendor/github.com/kubernetes-csi/csi-test/hack/_apitest/api_test.go
  vendor/github.com/kubernetes-csi/csi-test/hack/_embedded/embedded_test.go
  vendor/github.com/kubernetes-csi/csi-test/hack/e2e.sh
  vendor/github.com/kubernetes-csi/csi-test/mock/README.md
  vendor/github.com/kubernetes-csi/csi-test/mock/cache/SnapshotCache.go
  vendor/github.com/kubernetes-csi/csi-test/mock/main.go
  vendor/github.com/kubernetes-csi/csi-test/mock/mocksecret.yaml
  vendor/github.com/kubernetes-csi/csi-test/mock/service/controller.go
  vendor/github.com/kubernetes-csi/csi-test/mock/service/identity.go
  vendor/github.com/kubernetes-csi/csi-test/mock/service/node.go
  vendor/github.com/kubernetes-csi/csi-test/mock/service/service.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/README.md
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/cleanup.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/tests.go
  vendor/github.com/kubernetes-csi/csi-test/test/co_test.go
  vendor/github.com/kubernetes-csi/csi-test/test/driver_test.go
  vendor/github.com/kubernetes-csi/csi-test/utils/safegoroutinetester.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#90 Temporarily calling CSINodeInfo API directly instead of using a lister
  cmd/csi-attacher/main.go
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/trivial_handler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#92 Update to CSI v1.0.0 release
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/container-storage-interface/spec/csi.proto
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/spec.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#93 Create v1.0.0 containers
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#98 Implement PUBLISH_READONLY capability
  cmd/csi-attacher/main.go
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#106 Use logging util
  Gopkg.lock
  Gopkg.toml
  pkg/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.lock
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-lib-utils/LICENSE
  vendor/github.com/kubernetes-csi/csi-lib-utils/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/OWNERS
  vendor/github.com/kubernetes-csi/csi-lib-utils/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/SECURITY_CONTACTS
  vendor/github.com/kubernetes-csi/csi-lib-utils/code-of-conduct.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/.gitignore
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csi.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest/csitest.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#107 Cherry pick #106 to release-1.0: Use logging util
  Gopkg.lock
  Gopkg.toml
  pkg/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.lock
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-lib-utils/LICENSE
  vendor/github.com/kubernetes-csi/csi-lib-utils/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/OWNERS
  vendor/github.com/kubernetes-csi/csi-lib-utils/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/SECURITY_CONTACTS
  vendor/github.com/kubernetes-csi/csi-lib-utils/code-of-conduct.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/.gitignore
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csi.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest/csitest.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
