Repository kubernetes-csi/external-attacher, pull requests merged in 2019-08, with the labels that each got.

#165 Fixed ControllerUnpublish error handling
  pkg/attacher/attacher.go
  pkg/attacher/attacher_test.go
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-action-required, size/L

#167 Prow update master
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#168 1.2: Fixed ControllerUnpublish error handling
  pkg/attacher/attacher.go
  pkg/attacher/attacher_test.go
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#170 1.0: Fixed ControllerUnpublish error handling
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#169 1.1: Fixed ControllerUnpublish error handling
  pkg/attacher/attacher.go
  pkg/attacher/attacher_test.go
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#174 Fix name of retry-interval-end parameter
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#176 Update CHANGELOG for new external attacher release
  CHANGELOG-1.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#173 2.0 prep: Remove deprecated flags
  Gopkg.lock
  README.md
  cmd/csi-attacher/main.go
  deploy/kubernetes/deployment.yaml
  deploy/kubernetes/rbac.yaml
  doc/development.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/deprecatedflags/deprecatedflags.go
  vendor/k8s.io/csi-api/LICENSE
  vendor/k8s.io/csi-api/pkg/apis/csi/v1alpha1/doc.go
  vendor/k8s.io/csi-api/pkg/apis/csi/v1alpha1/register.go
  vendor/k8s.io/csi-api/pkg/apis/csi/v1alpha1/types.go
  vendor/k8s.io/csi-api/pkg/apis/csi/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/csi-api/pkg/client/clientset/versioned/clientset.go
  vendor/k8s.io/csi-api/pkg/client/clientset/versioned/doc.go
  vendor/k8s.io/csi-api/pkg/client/clientset/versioned/scheme/doc.go
  vendor/k8s.io/csi-api/pkg/client/clientset/versioned/scheme/register.go
  vendor/k8s.io/csi-api/pkg/client/clientset/versioned/typed/csi/v1alpha1/csi_client.go
  vendor/k8s.io/csi-api/pkg/client/clientset/versioned/typed/csi/v1alpha1/csidriver.go
  vendor/k8s.io/csi-api/pkg/client/clientset/versioned/typed/csi/v1alpha1/csinodeinfo.go
  vendor/k8s.io/csi-api/pkg/client/clientset/versioned/typed/csi/v1alpha1/doc.go
  vendor/k8s.io/csi-api/pkg/client/clientset/versioned/typed/csi/v1alpha1/generated_expansion.go
  vendor/k8s.io/csi-api/pkg/client/informers/externalversions/csi/interface.go
  vendor/k8s.io/csi-api/pkg/client/informers/externalversions/csi/v1alpha1/csidriver.go
  vendor/k8s.io/csi-api/pkg/client/informers/externalversions/csi/v1alpha1/csinodeinfo.go
  vendor/k8s.io/csi-api/pkg/client/informers/externalversions/csi/v1alpha1/interface.go
  vendor/k8s.io/csi-api/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/csi-api/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/csi-api/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/csi-api/pkg/client/listers/csi/v1alpha1/csidriver.go
  vendor/k8s.io/csi-api/pkg/client/listers/csi/v1alpha1/csinodeinfo.go
  vendor/k8s.io/csi-api/pkg/client/listers/csi/v1alpha1/expansion_generated.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-action-required, size/XXL

#177 2.0 prep: Revert "Revert "Use patch to replace update""
  Gopkg.lock
  deploy/kubernetes/rbac.yaml
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/trivial_handler_test.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-action-required, size/XL

#175 make worker-threads configurable
  README.md
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S
