Repository kubernetes-csi/external-attacher, pull requests merged in 2019-06, with the labels that each got.

#152 update rbac for secret
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#156 Bump version of csi-translation-lib to master to include translation lib for Azure Disk/File, updates for AWS, GCE, OpenStack
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/csi-translation-lib/translate.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note, size/XL

#157 Revert "Use patch to replace update"
  Gopkg.lock
  deploy/kubernetes/rbac.yaml
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/trivial_handler_test.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note-none, size/XL

#155 Add 1.2 changelog with notable feature of inline volume migration
  CHANGELOG-1.2.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
