Repository kubernetes-csi/external-attacher, pull requests merged in 2019-04, with the labels that each got.

#136 Add CHANGELOG for v1.1
  CHANGELOG-1.1.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#137 fix changelog indent and update README
  CHANGELOG-1.1.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#139 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#138 Prow testing
  .prow.sh
  release-tools/.prow.sh
  release-tools/README.md
  release-tools/build.make
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/util.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#140 update to Go 1.12.4
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#141 Added backoff parameters to external attacher
  cmd/csi-attacher/main.go
  pkg/controller/controller.go
  pkg/controller/framework_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#142 Added new command line arguments to README.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#144 fix default leader election type
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#146 Update RBAC for CSINode
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#145 Cherry pick #144 to release-1.1: fix default leader election type
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#147 Cherry-pick #146 to release-1.1: Update RBAC for CSINode
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#148 Add changelog for 1.1.1
  CHANGELOG-1.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
