Repository kubernetes-csi/external-attacher, pull requests merged in 2019-09, with the labels that each got.

#180 Update csi-release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#181 Add v2.0 changelog
  CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#182 Exit on connection loss
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#183 Update 2.0 changelog
  CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS
