Repository kubernetes-csi/external-attacher, pull requests merged in 2020-04, with the labels that each got.

#220 Add CHANGELOG for v2.2.0
  CHANGELOG-2.2.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#222 Decrease recommended version
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#200 update volumeAttachment to v1
  cmd/csi-attacher/main.go
  deploy/kubernetes/rbac.yaml
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/trivial_handler.go
  pkg/controller/trivial_handler_test.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-action-required, size/L

#193 Use v1.CSINode in the external-attacher
  cmd/csi-attacher/main.go
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#227 Update VolumeAttachment.Finalizers as separate subresource in markAsDetatched
  pkg/controller/csi_handler_test.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/L
