Repository kubernetes-csi/external-attacher, pull requests merged in 2020-12, with the labels that each got.

#279 Introduce http-endpoint flag
  README.md
  cmd/csi-attacher/main.go
  deploy/kubernetes/deployment.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S

#280 Add server listening log; fix wrong address logged in listening error
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#281 Documentation fixes for HTTP endpoint
  README.md
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#283 Add changelog for v3.1.0
  CHANGELOG/CHANGELOG-3.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L
