Repository kubernetes-csi/external-attacher, pull requests merged in 2020-01, with the labels that each got.

#199 Prepare release 2.1
  CHANGELOG-2.1.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#204 Fix metrics typos
  README.md
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#205 fix incorrect link
  doc/development.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#206 Remove unused leaderElectionTypeConfigMaps const
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#209 fix: go module requirements for semantic versioning
  cmd/csi-attacher/main.go
  go.mod
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/trivial_handler_test.go
  v2/README.md
  v2/cmd/csi-attacher/main.go
  v2/pkg/attacher/attacher.go
  v2/pkg/attacher/attacher_test.go
  v2/pkg/attacher/lister.go
  v2/pkg/controller/controller.go
  v2/pkg/controller/controller_test.go
  v2/pkg/controller/csi_handler.go
  v2/pkg/controller/csi_handler_test.go
  v2/pkg/controller/framework_test.go
  v2/pkg/controller/trivial_handler.go
  v2/pkg/controller/trivial_handler_test.go
  v2/pkg/controller/util.go
  v2/pkg/controller/util_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/M

#210 Cherry-pick to 2.1: go module requirements for semantic versioning
  cmd/csi-attacher/main.go
  go.mod
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/trivial_handler_test.go
  v2/README.md
  v2/cmd/csi-attacher/main.go
  v2/pkg/attacher/attacher.go
  v2/pkg/attacher/attacher_test.go
  v2/pkg/attacher/lister.go
  v2/pkg/controller/controller.go
  v2/pkg/controller/controller_test.go
  v2/pkg/controller/csi_handler.go
  v2/pkg/controller/csi_handler_test.go
  v2/pkg/controller/framework_test.go
  v2/pkg/controller/trivial_handler.go
  v2/pkg/controller/trivial_handler_test.go
  v2/pkg/controller/util.go
  v2/pkg/controller/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#211 Add changelog for 2.1.1 release
  CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
