Repository kubernetes-csi/external-attacher, pull requests merged in 2020-07, with the labels that each got.

#237 master: update release-tools
  release-tools/cloudbuild.yaml
  release-tools/filter-junit.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#242 Use separate client for leader election
  cmd/csi-attacher/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#238 Rework to klog/v2
  cmd/csi-attacher/main.go
  go.mod
  pkg/attacher/attacher.go
  pkg/controller/controller.go
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/trivial_handler.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#239 Prepare v3 release
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-2.0.md
  CHANGELOG/CHANGELOG-2.1.md
  CHANGELOG/CHANGELOG-2.2.md
  CHANGELOG/CHANGELOG-3.0.md
  README.md
  cmd/csi-attacher/main.go
  go.mod
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
  pkg/controller/trivial_handler_test.go
  v2/README.md
  v2/cmd/csi-attacher/main.go
  v2/pkg/attacher/attacher.go
  v2/pkg/attacher/attacher_test.go
  v2/pkg/attacher/lister.go
  v2/pkg/controller/controller.go
  v2/pkg/controller/controller_test.go
  v2/pkg/controller/csi_handler.go
  v2/pkg/controller/csi_handler_test.go
  v2/pkg/controller/framework_test.go
  v2/pkg/controller/trivial_handler.go
  v2/pkg/controller/trivial_handler_test.go
  v2/pkg/controller/util.go
  v2/pkg/controller/util_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L
