Repository kubernetes-csi/external-attacher, pull requests merged in 2020-08, with the labels that each got.

#246 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
  release-tools/travis.yml
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#244 Fixes ReconcileVA for non-migratable drivers
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/framework_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/L

#248 Corrections in the attacher sidecar documentation
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#249 Update 3.0 changelog
  CHANGELOG/CHANGELOG-3.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#251 Bump kube version to 1.19.0 and dependencies to 0.19.0
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/lifecycle.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/net/util.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/LICENSE
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/allocator.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/doc.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/fields.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/list.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/map.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/structreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/value.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valuereflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valueunstructured.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#250 Bump go version to 1.15
  go.mod
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#252 Update 3.0 changelog
  CHANGELOG/CHANGELOG-3.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
