Repository kubernetes-csi/external-attacher, pull requests merged in 2021-08, with the labels that each got.

#318 reuse same CSI controller client
  pkg/attacher/attacher.go
  pkg/attacher/lister.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#321 Update k8s dependencies to v1.22.0
  README.md
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, sig/storage, size/L

#308 Map PV access modes to CSI access modes based on driver capability
  cmd/csi-attacher/main.go
  go.mod
  go.sum
  pkg/controller/csi_handler.go
  pkg/controller/csi_handler_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/accessmodes/access_modes.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#323 Add CHANGELOG for v3.3.0
  CHANGELOG/CHANGELOG-3.2.md
  CHANGELOG/CHANGELOG-3.3.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L, approved

#325 Clean up .travis.yml
  .travis.yml
  README.md
Labels: cncf-cla: yes, kind/cleanup, lgtm, release-note-none, approved, size/XS, ok-to-test

#324 Clean up unused vars, funcs and types
  cmd/csi-attacher/main.go
  pkg/attacher/attacher.go
  pkg/attacher/attacher_test.go
  pkg/controller/csi_handler.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: cncf-cla: yes, size/M, kind/cleanup, lgtm, release-note-none, approved, ok-to-test
