Repository kubernetes-csi/external-attacher, pull requests merged in 2021-12, with the labels that each got.

#336 Fix get nodeid from va.annotation directly
  pkg/controller/csi_handler.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS, ok-to-test

#338 Skip processing of ManagedFields changes
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: cncf-cla: yes, lgtm, size/S, release-note-none, approved, ok-to-test

#340 Add CHANGELOG for v3.4
  CHANGELOG/CHANGELOG-3.4.md
Labels: cncf-cla: yes, size/M, lgtm, kind/documentation, release-note-none, approved
