Repository kubernetes-csi/external-attacher, pull requests merged in 2022-06, with the labels that each got.

#359 bump up gopkg.in/yaml.v3 to address CVE-2022-28948
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/M, lgtm, release-note-none, approved, ok-to-test

#360 master: update release-tools
  release-tools/prow.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#362 release-3.3: update release-tools
  release-tools/prow.sh
  release-tools/verify-spelling.sh
Labels: cncf-cla: yes, lgtm, size/S, release-note-none, approved

#357 Add v3.5 changelog
  CHANGELOG/CHANGELOG-3.5.md
Labels: cncf-cla: yes, lgtm, kind/documentation, release-note-none, size/L, approved

#358 Change Fstype default to emptyString from ext4
  README.md
  cmd/csi-attacher/main.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-action-required, approved, size/XS
