Repository kubernetes-csi/external-attacher, pull requests merged in 2023-09, with the labels that each got.

#481 Add changelog for v4.4
  CHANGELOG/CHANGELOG-4.4.md
Labels: cncf-cla: yes, lgtm, kind/documentation, release-note-none, size/L, approved

#483 release-tool update
  release-tools/SIDECAR_RELEASE_PROCESS.md
Labels: cncf-cla: yes, lgtm, size/S, release-note-none, approved

#491 Enable dependabot raising PR by groups
  .github/dependabot.yaml
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/S, release-note-none, approved
