Repository kubernetes-csi/external-attacher, pull requests merged in 2023-12, with the labels that each got.

#517 Update release tools to fix broken image build pipeline
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-modules-update.sh
  release-tools/prow.sh
Labels: cncf-cla: yes, lgtm, release-note-none, size/L, approved

#519 Update dependency go modules for k8s v1.29.0
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/M, lgtm, release-note, approved

#521 Update csi-lib-utils to v0.17.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/S, release-note-none, approved

#524 Update go modules
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/S, release-note-none, approved

#525 Changelog for v4.4.3
  CHANGELOG/CHANGELOG-4.4.md
Labels: cncf-cla: yes, lgtm, size/S, release-note-none, approved
